package com.reflexos.ai;

import com.reflexos.ai.dto.AiMeetingResponse;
import com.reflexos.project.Project;
import com.reflexos.project.ProjectRepository;
import com.reflexos.task.Task;
import com.reflexos.task.TaskRepository;
import dev.langchain4j.model.chat.ChatLanguageModel;
import com.reflexos.task.dto.TaskResponse;
import com.reflexos.task.TaskStatus;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class AIService {

    private final ChatLanguageModel chatLanguageModel;
    private final TaskRepository taskRepository;
    private final ProjectRepository projectRepository;

    @Transactional
    public List<TaskResponse> generateSprintPlan(String prompt, UUID projectId) {
        Project project = projectRepository.findById(projectId).orElseThrow();

        String systemPrompt = "You are an expert Agile Project Manager. " +
                "Given the following user request to build a project, break it down into 5 to 10 high-level actionable tasks. " +
                "Return ONLY a comma-separated list of task titles. Do not include numbers, bullets, or explanations. " +
                "Example output: Setup Backend,Setup Database,Create Authentication,Create UI";

        String userPrompt = "Project request: " + prompt;

        String response = chatLanguageModel.generate(systemPrompt + "\n" + userPrompt);
        log.info("AI generated sprint plan: {}", response);

        List<String> taskTitles = Arrays.stream(response.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());

        List<Task> tasks = taskTitles.stream().map(title -> 
            Task.builder()
                .title(title)
                .description("Generated by AI")
                .status(TaskStatus.TODO)
                .project(project)
                .build()
        ).collect(Collectors.toList());

        return taskRepository.saveAll(tasks).stream()
                .map(this::mapToResponse)
                .collect(Collectors.toList());
    }

    @Transactional
    public AiMeetingResponse analyzeMeeting(String transcript, UUID projectId) {
        Project project = projectRepository.findById(projectId).orElseThrow();

        // 1. Generate Summary
        String summaryPrompt = "You are an AI Executive Assistant. Summarize the following meeting transcript into a concise executive summary. Return ONLY the summary text.\n\nTranscript: " + transcript;
        String summary = chatLanguageModel.generate(summaryPrompt).trim();
        log.info("AI Meeting Summary: {}", summary);

        // 2. Extract Action Items
        String actionPrompt = "You are an AI Executive Assistant. Extract all action items or tasks from the following meeting transcript. Return ONLY a comma-separated list of task titles. Do not include numbers, bullets, or explanations. If there are no tasks, return an empty string.\n\nTranscript: " + transcript;
        String actionItemsStr = chatLanguageModel.generate(actionPrompt);
        log.info("AI Meeting Action Items: {}", actionItemsStr);

        List<TaskResponse> taskResponses = List.of();
        if (actionItemsStr != null && !actionItemsStr.trim().isEmpty()) {
            List<String> taskTitles = Arrays.stream(actionItemsStr.split(","))
                    .map(String::trim)
                    .filter(s -> !s.isEmpty())
                    .collect(Collectors.toList());

            List<Task> tasks = taskTitles.stream().map(title ->
                    Task.builder()
                            .title(title)
                            .description("Extracted from meeting notes")
                            .status(TaskStatus.TODO)
                            .project(project)
                            .build()
            ).collect(Collectors.toList());

            taskResponses = taskRepository.saveAll(tasks).stream()
                    .map(this::mapToResponse)
                    .collect(Collectors.toList());
        }

        return AiMeetingResponse.builder()
                .summary(summary)
                .actionItems(taskResponses)
                .build();
    }

    private TaskResponse mapToResponse(Task task) {
        return TaskResponse.builder()
                .id(task.getId())
                .title(task.getTitle())
                .description(task.getDescription())
                .status(task.getStatus())
                .projectId(task.getProject().getId())
                .sprintId(task.getSprint() != null ? task.getSprint().getId() : null)
                .assigneeId(task.getAssignee() != null ? task.getAssignee().getId() : null)
                .assigneeName(task.getAssignee() != null ? task.getAssignee().getName() : null)
                .createdAt(task.getCreatedAt())
                .build();
    }
}
